### ISSUE TITLE
Can't build with vite@4, Is it really abandoned? 

### ISSUE THREAD

**Issue by jsprog** [alloc/vite-plugin-compress#20]
This plugin is really broken with vite@4. Just, create a vite project based on one of the available templates, then use this plugin as documented in readme. I even tried it as a regular dependency and again as a dev dependency but failed.

problem 1:
```
failed to load config from /home/linuxuser/my-vue-app/vite.config.js
error during build:
TypeError: compress is not a function
    at file:///home/linuxuser/my-vue-app/vite.config.js.timestamp-1689109439253-f0f6a29d5d51b.mjs:8:5
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
```

problem 2 - compress.default() instead of compress() didn't help at all, and I'm receiving this error:
```
error during build:
TypeError: Cannot set properties of undefined (setting 'writeBundle')
    at configResolved (/home/linuxuser/my-vue-app/node_modules/vite-plugin-compress/dist/plugin.js:39:30)
    at file:///home/linuxuser/my-vue-app/node_modules/vite/dist/node/chunks/dep-210e5610.js:65822:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///home/linuxuser/my-vue-app/node_modules/vite/dist/node/chunks/dep-210e5610.js:65822:14)
    at async build (file:///home/linuxuser/my-vue-app/node_modules/vite/dist/node/chunks/dep-210e5610.js:47747:20)
    at async CAC.<anonymous> (file:///home/linuxuser/my-vue-app/node_modules/vite/dist/node/cli.js:822:9)
```
Please, archive this repository if it's really abandoned

**Comment by jsprog** [comment]
Already moved to [vite-plugin-compression](https://github.com/nonzzz/vite-plugin-compression) and it's maintained.
